### ISSUE TITLE
Link probably broken

### ISSUE THREAD

**Issue by hugolmn** [martindurant/dask-tutorial-scipy-2018#8]
The first link in the README seems to be broken:
> Materials for the [Dask tutorial at SciPy 2018](https://scipy2018.scipy.org/ehome/index.php?eventid=299527&tabid=711308&cid=2229599&sessionid=21547348&sessionchoice=1&).
```XML
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>986A29836773E98C</RequestId>
<HostId>
zQWXaMVTNJhl+or2vFVygjWA3Nzb4PxsU5Gv08H4vAl3BuHNtG+PmyIvs2GGZ4ohsgwUDOtuoGs=
</HostId>
</Error>
```

Is there anything that can be done to fix this ? Do I have to be an attendee ?

**Comment by martindurant** [comment]
I suppose they stopped that server?
You probably want the similar material at https://github.com/dask/dask-tutorial

**Comment by hugolmn** [comment]
Perfect, thank you very much :)

**Comment by hugolmn** [comment]
Perfect, thank you very much :)
